# Generated by Django 4.1 on 2022-09-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0008_buyeraccount"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="user_adress",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="user_account.selleraccount",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seller_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_account.selleraccount",
            ),
        ),
    ]
