# Generated by Django 4.1 on 2022-09-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="seller_account",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
