# Generated by Django 4.1 on 2022-09-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0002_selleraccount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SellerAccount",
        ),
    ]
