# Generated by Django 4.1 on 2022-09-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0004_selleraccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selleraccount",
            name="is_seller",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
