# Generated by Django 4.1 on 2022-09-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0005_alter_selleraccount_is_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="selleraccount",
            name="seller_password",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
