# Generated by Django 4.1 on 2022-09-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0006_selleraccount_seller_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selleraccount",
            name="seller_password",
        ),
    ]
